openapi: '3.0.2'
info:
  description: Third Library API
  title: General API for the Library
  version: "1.0.0"
servers:
- url: /api/v1/

components:
  schemas:
    Book:
      description: Represents a book in search results
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        pubDate:
          type: string
          format: date-time
        publisher:
          type: string
    SearchResults:
      description: Search results containing found books and metadata about search.
      type: object
      properties:
        count:
          type: integer
        query:
          type: object
        results:
          type: array
          items:
            $ref: '#/components/schemas/Book'
    SearchQuery:

paths:
  /test:
    get:
      description: Test endpoint for development. TODO- DELETE THIS
      tags:
        - Development
      operationId: v1.general.test
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            minimum: 1
            maximum: 50
      responses:
        200:
          description: Hello world!
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string

  /search:
    get:
      description: Search for books.
      tags:
        - Search
      parameters:
        - in: query
          name: q
          required: true
      responses:
        200:
          description: Search results
        400:
          description: Bad request
        404:
          description: Not found

  /license:
    get:
      description: Get the license for a particular book
      tags:
        - License
      parameters:
        - in: path
          name: uuid
          required: true